### ISSUE TITLE
not issue, BKM request for utilization

### ISSUE THREAD

**Issue by kobuworks** [yas-sim/openvino-model-server-wrapper#1]
Hi yas-sim, 
thanks a lot for sharing wonderful code.
I'm not good in model server, would you kindly let me know what is the next step for this?
"OVMS will start serving the Resnet-50 model as model-name='resnet_50', model-version=1, and gRPC-port=9000."
Server w/ resnet is running, how it can be utilized?
thanks,
p.s.:
tensorflow installation was required for model converter.
another curious thing is you use "python and python3", I just used python3 only.

BR/Kobu

**Comment by yas-sim** [comment]
Hi Kobu,

Thanks for your interest to my project.

After you started the OVMS, you can run your inference client code or my sample client code such as 'ovms_wrapper_test.py' to run inference.
You can run the client code from any PC or node as long as it's IP reachable to the OVMS.

For the dependency, I'm trying to remove the tensorflow dependency but the tensorflow_serving_api is heavily depend on the tensorflow so it is difficult. I tried to generate protobuf handler code from .proto files but the new handler conflicts with the existing handlers and caused complex issues. Still I'm looking for a better way to resolve it and remove tensorflow dependency.

You can use 'python' in the 'venv' envronment even though you need to use 'python3' on the native host environment.

Regards,
Shimura

**Comment by yas-sim** [comment]
Kobu,

> tensorflow installation was required for model converter.

Thanks for letting me know it. Yes. I noticed it but failed to mention it in the document. I'll reflect it soon.

Regards,
Shimura

**Comment by kobuworks** [comment]
Hi yas-sim,
thanks a lot for your prompt resp, though some errors were found, now it's clear what I should do next!
Model server system installation was complicated in the past, your code & instruction is great, now my model server is running.
thanks a lot,
BR/Kobu

> Hi Kobu,
> 
> Thanks for your interest to my project.
> 
> After you started the OVMS, you can run your inference client code or my sample client code such as 'ovms_wrapper_test.py' to run inference. You can run the client code from any PC or node as long as it's IP reachable to the OVMS.
> 
> For the dependency, I'm trying to remove the tensorflow dependency but the tensorflow_serving_api is heavily depend on the tensorflow so it is difficult. I tried to generate protobuf handler code from .proto files but the new handler conflicts with the existing handlers and caused complex issues. Still I'm looking for a better way to resolve it and remove tensorflow dependency.
> 
> You can use 'python' in the 'venv' envronment even though you need to use 'python3' on the native host environment.
> 
> Regards, Shimura
